### ISSUE TITLE
[Quilt] [1.19.4] Client crashes

### ISSUE THREAD

**Issue by k2helix** [Quplet/Qu-Enchantments#10]
Hello, after installing Qu Enchantments on latest Quilt on 1.19.4, my client crashes. Here is the crash log: https://mclo.gs/60ASTCB
It is caused by this mod as removing it makes Minecraft boot correctly

**Comment by Quplet** [comment]
Ok, I see what's wrong. It's technically both my mod and another mod you're using that are both trying to add a shield enchantment target. If you remove the other mod that does it it will work as well.

Do you know what other mod is adding the shield enchanting functionality? I can try to do a couple things to get them to work together.

**Comment by k2helix** [comment]
No idea what other mod is doing it. Maybe IlMusu's Enchantments

**Comment by Quplet** [comment]
I haven't been able to determine which mod you're using that conflicting with mine, but I've made some changes that should fix the conflict. Would you mind testing the latest build here to see if it works?

**Comment by k2helix** [comment]
> I haven't been able to determine which mod you're using that conflicting with mine, but I've made some changes that should fix the conflict. Would you mind testing the latest build here to see if it works?

Hi again, the latest release candidate works fine! Feel free to close this issue
