### ISSUE TITLE
[Fabric] [1.19.2] Server crashes

### ISSUE THREAD

**Issue by pewblaze** [Quplet/Qu-Enchantments#9]
Hi the server crashes while fighting with Incendium in the Nether against an Illusioner D: 
It mentions this mod first. I also have ServerCore and its also mentioned but idk which one causes it.

crash report + latest.log:
https://gist.github.com/pewblaze/df1cd7749c4c1a4a3786cbbe99f7146e

qu-enchantments-1.2.3-1.19

**Comment by Quplet** [comment]
I see the problem. I've updated a few lines that should prevent it. I'll push an update soon. Thanks for reporting!
